name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
       docker build -f Dockerfile -t test:test1 .
       docker login --username admin --password-stdin < ~/my_password http://localhost:8081/repository/test-repo/
       docker push http://27.5.163.155:8081/repository/test-repo/test1:test1
