name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
       docker build -f Dockerfile -t test:test1 .
       sudo systemctl daemon-reload #THIS IS RESCUE COMMAND…
       sudo systemctl restart docker
       sudo systemctl status docker
       docker login http://localhost:8081/
       docker push http://127.0.0.1:8081/repository/test-repo/test1:test1
